### ISSUE TITLE
Toplevel issue: For deploy!

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#211]
Top level issue meant to roundup all the things we need to address prior to deploy. 

It think if we address all of these things, we should have a deployable interface! I've tried to group issues by type, and listed roughly in order of priority. 

### Things that (may) require changes to database schema or definition
- [x] **Issue #204: adding 'project shortname' field**
       We are using a consistent 'project shortname' that incorporates the Qiita ID so that data
       can be automatically transferred to a project directory on demux. Needs to be in DB. **easy**
- [ ] **Issue #199: performance enhancement**
       Currently experiencing large slowdowns with > a few hundred plates in DB. **hard?**
       Would also be good to look at how sample names (blanks, and concentrations) are queried for plates, for example see the changes in #229 

### Bug fixes
- [x] **Issue #203: Fix amplicon quantification and pooling**
       Currently the amplicon pooling isn't sensible. WIP. 
- [x] **Issue #206: Pooling display updating**
       Currently, recomputing pooling leads to overlapping duplicate plot elements

### Important feature additions
- [x] **Issues #209** We scan barcodes for plating samples with AGP. The scanner doesn't include 
        the prepended  study number, so doesn't match up to the database. Should not display study
        # (#209). 
- [x] **Issue #210: plating and naming samples** May also help with running out of room in 
        cells (#210) **easy**
- [x] **Issue  #195: quantify plate interface**
       Plate quantification values need to be able to retrieved and viewed, and also updatable.
- [x] **Issue #214: choose a quantification**
       There's no way to distinguish between or choose a quantification for a plate when displaying or
       normalizaing. 
- [x] **Issue #168: create DNA plate w/o extraction**
       Need a sensible way to process already-extracted DNA from collaborators
- [ ] **Issue #77: plate history**
       Need to be able to see the upstream and downstream steps of a plate
- [x] **Issue #219: prep info**
       Need to be able to export a Qiita-compatible prep info file once a sequencing run is made with
       all the nice info we've stored in the db

**Comment by ElDeveloper** [comment]
@tanaes, thanks for putting this together, this is very helpful!
