### ISSUE TITLE
Toplevel issue:  for codesprint!

### ISSUE THREAD

**Issue by tanaes** [jdereus/labman#255]
## Small interface tweaks

- [x] **Issue #251: add 'eyeball' eye-con to pool list so pooling picklist files can be downloaded
    Currently, there is no way to get back to re-download a pooling picklist. We need a new icon 
    for pools analogous to the one for plates.**
- [ ] Issue #252: add visual plate map to gDNA compression page. 
    This will help the wet lab to make sure the source plates are positioned correctly.
- [ ] Issue #254: Update process.py's _format_sample_sheet to use Process._get_date_format()
    Reducing code duplication
- [ ] Issue #249: Add tooltips to pooling interface to explain parameter values
- [ ] Issue #246: Expose date stamp for plate creation in plate list interfaces
    This will help distinguish among different plates and find the one you're looking for.
- [ ] Issue #245: Add drop-down plate-type filter to Quantify Plate interface
    So you don't have to wade through every type of plate when you're looking for one.
- [x] **Issue #242: Expose plate-level comments in sample plating interface
    This extends the functionality added in PR #224 to the "plating samples" interface**
- [ ] **Issue #257: Separate DBs and connect via API
    Update LabMan to query study and sample info from Qiita DB via API rather than relying on shared
    db.**

## Slightly more interesting
- [ ] Issue #244: Add comments to multiple wells based on selection
    Be able to drag a selection of wells in the "plating samples" interface, and apply comment
    to all of the wells in that selection at once.
- [x] **Issue #239: add per-lane pool assignment in 'Prepare sequencing run' interface
    Currently, there is no mechanism to assign sequence pools to individual lanes (e.g. 8
    lanes of HiSeq4000 or 2 lanes of HiSeq2500).**

## Bugs
- [x] **Issue #243: Copy and pasting in plates stopped working
    Should be able to copy from a tab-delimited text file and paste in "plating samples" interface. 
    This could be made Slightly More Interesting by needing to prepend the study number.**
- [x] **Issue #241: changing plate type in 'plate samples' interface should not add additional plates**
