### ISSUE TITLE
Toplevel: For Soft Launch

### ISSUE THREAD

**Issue by AmandaBirmingham** [jdereus/labman#263]
The issues on this list are all those that I know of that we MUST address before soft launch in the wet lab (soft launch = wet lab uses labman alongside existing processes, treats existing processes as gold standard in case of disagreement).  

- [x] Issue #243 Copy and pasting in plates stopped working
Assigned to @ElDeveloper, bug, size unknown, pull request is ready for @wasade 

- [x] Issue #251 Extend pool list to offer re-download of pool files for plate pools
Assigned to @AmandaBirmingham, new feature, small, pull request is ready

- [x] Issue #242 Expose plate-level comments in sample plating and gdna extraction interfaces
Assigned to @ElDeveloper, new feature, small

- [x] Issue #239 Include lane column/number in amplicon sample sheets for multilane sequencers
Assigned to @qiyunzhu, bug, small

- [ ] Issue #262 Populate real labman db with needed real equipment/etc records
Assigned to @tanaes and @antgonza , new feature, small to medium, change request submitted on PR

- [x] Issue #270 Move labman tables out of qiita schema and into own new schema
Assigned to @antgonza, new feature, small

- [ ] Issue #272 Duplicate key error when pasting platemap into sample plating page
Assigned to @AmandaBirmingham and @ElDeveloper, bug, pull request is submitted

- [ ] Issue #273 Sample plating must take in tube ids (anonymized_name) not sample_id
Unassigned, bug (code works as written but was written to inaccurate specifications), requires further discussion before scoping
Note: Amanda, Gail, Austin to discuss 08/01 then follow up with Greg

- [ ] Issue #274 add https
Assigned to @antgonza, new feature, small, change request submitted on PR

- [ ] Issue #282 Collect information & files to test amplicon pipeline on an existing experiment
Assigned to @ElDeveloper, testing prep, small

- [x] Issue #283 Collect information & files to test shotgun pipeline on an existing experiment
Assigned to @ElDeveloper, testing prep, small

**Comment by AmandaBirmingham** [comment]
Updating this issue is becoming a pain, so I'm switching over to using the Github milestone tagging: all issues that must be closed before soft launch are now tagged with the "Soft Launch" milestone.
